#!/bin/bash
# RayOS Test Suite Quick Reference
#
# Fast guide to running tests and verifying RayOS functionality

echo "RayOS Test Suite Quick Reference"
echo "=================================="
echo ""
echo "QUICK START:"
echo "  cd /home/noodlesploder/repos/RayOS"
echo "  ./scripts/test-all-headless.sh"
echo ""
echo "INDIVIDUAL TESTS:"
echo "  ./scripts/test-boot-headless.sh              # Basic boot (30s)"
echo "  ./scripts/test-boot-aarch64-headless.sh      # ARM64 boot (30s)"
echo "  ./scripts/test-boot-ai-headless.sh           # AI bridge (30s)"
echo "  ./scripts/test-chainloading.sh               # Boot media (20s)"
echo "  ./scripts/test-conductor-autostart.sh        # Conductor service (20s)"
echo "  ./scripts/test-installer-boot-headless.sh    # Installer boot (30s)"
echo ""
echo "CUSTOM TIMEOUTS:"
echo "  TIMEOUT_SECS=120 ./scripts/test-all-headless.sh      # 2 minute timeout"
echo "  TIMEOUT_SECS=45 ./scripts/test-all-headless.sh       # 45 second timeout (CI mode)"
echo ""
echo "BUILD & TEST WORKFLOW:"
echo "  1. Build kernel:  cd crates/kernel-bare && cargo build --release"
echo "  2. Build boot:    cd crates/bootloader && cargo build --release"
echo "  3. Stage image:   ./scripts/stage-rayos-usb.sh (if needed)"
echo "  4. Run tests:     ./scripts/test-all-headless.sh"
echo ""
echo "TEST RESULTS:"
echo "  ✅ PASS   - Test executed and assertions passed"
echo "  ⏱️  TIMEOUT - Test running (interactive/long-running) - this is OK"
echo "  ❌ FAIL   - Test executed but assertions failed"
echo ""
echo "KEY FILES:"
echo "  TEST_SUITE_STATUS.md              - Full status report"
echo "  scripts/test-all-headless.sh      - Main test harness"
echo "  scripts/test-boot-headless.sh     - Primary boot test"
echo "  crates/kernel-bare/src/main.rs    - Kernel source"
echo ""
echo "USEFUL COMMANDS:"
echo "  git log --oneline -10             - Recent commits"
echo "  git status                        - Current state"
echo "  cargo check                       - Quick compile check"
echo "  ls -lh build/rayos-*.img          - Check images exist"
echo ""
echo "FOR MORE INFO: cat TEST_SUITE_STATUS.md"
